const RESPONSE_STATUS = {
          OK: "OK",
          CREATED: "CREATED",
          NOT_FOUND: "NOT_FOUND",
          UNAUTHORIZED: "UNAUTHORIZED",
          UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
          INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
}

module.exports = RESPONSE_STATUS